dist: trusty

language: node_js

node_js:
  - "9.3.0"

before_install:

install:
  - npm install
  - nohup npm start ganache &
  - npm start migrateContracts

script:
  - npm run script daoCreateaoDutchX

notifications:
  slack: daostack:fGuaFPsiQiV5mgmzRcSzbYqw
